services:
  - type: web
    name: sat-flask-app
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PORT
        value: 10000
